In [35]:
from time import time
import numpy as np

class Sort(object):
    def __init__(self):
        self.__example = []

    @property
    def output(self):
        return self.__example

    def random_list(self, lenght):
        self.__example = np.random.randint(-1000, 1000, lenght)
        return self.__example

    def sorted_list(self, list_):
        return self.bubble_sort_for(list_)[0]

    def reversed_sorted_list(self, list_):
        return self.bubble_sort_for(list_)[0][::-1]

    def partially_sorted_list(self, list_):
        intermediate_list = sorted(list_)[:-(len(list_) // 10)]
        additional_list = np.random.randint(-1000, 1000, len(list_) // 10)
        return np.append(intermediate_list, additional_list)

    def bubble_sort_while(self, list_):
        index, flag = 0, False
        start_time = time()
        while True:
            if index == len(list_) - 1 and flag == True:
                index, flag = 0, False
            if index == len(list_) - 2 and flag == False:
                break
            if list_[index] > list_[index + 1]:
                list_[index], list_[index + 1] = list_[index + 1], list_[index]
                flag = True
            index += 1
        end_time = time()
        return list_, end_time - start_time

    def bubble_sort_for(self, list_):
        start_time = time()
        for i in range(len(list_)):
            for j in range(len(list_) - i - 1):
                if list_[j] > list_[j + 1]:
                    list_[j], list_[j + 1] = list_[j + 1], list_[j]
        end_time = time()
        return list_, end_time - start_time

    def rock_bubble_sort(self, list_):
        left_side, right_side = 0, len(list_) - 1

        start_time = time()

        while left_side < right_side:
            for i in range(right_side):
                if list_[i] > list_[i + 1]:
                    list_[i], list_[i + 1] = list_[i + 1], list_[i]
            right_side -= 1

            for i in range(right_side, left_side + 1, -1):
                if list_[i] < list_[i - 1]:
                    list_[i], list_[i - 1] = list_[i - 1], list_[i]
            left_side += 1

        end_time = time()
        return list_, end_time - start_time

    def quick_sort(self, list_):
        if len(list_) <= 1:
            return list_

        else:
            central = list_[0]
            left_side = [element for element in list_ if element < central]
            right_side = [element for element in list_ if element > central]
            return self.quick_sort(left_side) + [central] + self.quick_sort(right_side)
    
    def quick_sort_for_sorted(self, list_):
        if len(list_) <= 1:
            return list_

        else:
            central = list_[len(list_) // 2]
            left_side = [element for element in list_ if element < central]
            right_side = [element for element in list_ if element > central]
            return self.quick_sort(left_side) + [central] + self.quick_sort(right_side)
    
    def selection_sort(self, list_):
        for i in range(len(list_)):
            largest = i
            for j in range(i + 1, len(list_)):
                if list_[j] > list_[largest]:
                    largest = j
            list_[i], list_[largest] = list_[largest], list_[i]
        return list_
    
    def modified_selection_sort(self, list_):
        for i in range(len(list_) - 1, 0, -1):
            largest = i
            for j in range(i - 1, 0, -1):
                if list_[j] > list_[largest]:
                    largest = j
            list_[i], list_[largest] = list_[largest], list_[i]
        return list_




# print(example.bubble_sort_while(random_example))
# print(example.bubble_sort_for(random_example))

In [36]:
example = Sort()

# №10

Написать 4 функции порождения списка целых значений: отсортированного (по возрастанию и убыванию), случайного и почти отсортированного по возрастанию. Каждая функция принимает длину списка в качестве аргумента.

In [3]:
random_example = example.random_list(20)
random_example

array([ 137,  376, -851,  431, -684,  456,  135, -458, -240,  953,  646,
       -810, -313,  493,  362,  -82, -714,  418,  510,  425])

In [4]:
example.sorted_list(random_example)

array([-851, -810, -714, -684, -458, -313, -240,  -82,  135,  137,  362,
        376,  418,  425,  431,  456,  493,  510,  646,  953])

In [5]:
example.reversed_sorted_list(random_example)

array([ 953,  646,  510,  493,  456,  431,  425,  418,  376,  362,  137,
        135,  -82, -240, -313, -458, -684, -714, -810, -851])

In [6]:
example.reversed_sorted_list(random_example)

array([ 953,  646,  510,  493,  456,  431,  425,  418,  376,  362,  137,
        135,  -82, -240, -313, -458, -684, -714, -810, -851])

In [7]:
example.partially_sorted_list(random_example)

array([-851, -810, -714, -684, -458, -313, -240,  -82,  135,  137,  362,
        376,  418,  425,  431,  456,  493,  510,  328,  603])

# №12

Реализовать модификацию сортировки пузырьком: "камешек-пузырек" - с чередующимися проходами, приводящими к "всплытию" самого большого значения списка и "погружению" самого маленького значения из неотсортированной части списка.

In [8]:
example.rock_bubble_sort(random_example)[0]

array([-851, -810, -714, -684, -458, -313, -240,  -82,  135,  137,  362,
        376,  418,  425,  431,  456,  493,  510,  646,  953])

# №14

Реализовать модификацию сортировки пузырьком: "камешек-пузырек" - с чередующимися проходами, приводящими к "всплытию" самого большого значения списка и "погружению" самого маленького значения из неотсортированной части списка.

bubble_sort_for - сортировка пузырьком реализованная в классическом ее представлении

случайный список

In [9]:
start_time = time()
example.bubble_sort_for(example.random_list(10000))
end_time = time()
print(end_time - start_time)

19.51309895515442


сортированный список

In [10]:
test_time = sorted(example.random_list(10000))
start_time = time()
example.bubble_sort_for(test_time)
end_time = time()
print(end_time - start_time)

4.585827112197876


реверсд отсортированный список

In [11]:
test_time = sorted(example.random_list(10000))[::-1]
start_time = time()
example.bubble_sort_for(test_time)
end_time = time()
print(end_time - start_time)

10.49413251876831


частично отсортированный список

In [12]:
test_time = example.partially_sorted_list(example.random_list(10000))
start_time = time()
example.quick_sort(test_time)
end_time = time()
print(end_time - start_time)

0.8208422660827637


rock_bubble_sort - сортировка камешек - пузырек реализованная в импровизированным мной представлением

случайный список

In [13]:
start_time = time()
example.rock_bubble_sort(example.random_list(10000))
end_time = time()
print(end_time - start_time)

21.205727577209473


отсортированный список

In [14]:
test_time = sorted(example.random_list(10000))
start_time = time()
example.rock_bubble_sort(test_time)
end_time = time()
print(end_time - start_time)

5.807560682296753


реверсд отсортированный список

In [15]:
test_time = sorted(example.random_list(10000))[::-1]
start_time = time()
example.rock_bubble_sort(test_time)
end_time = time()
print(end_time - start_time)

12.269426345825195


частично отсортированный список

In [16]:
test_time = example.partially_sorted_list(example.random_list(10000))
start_time = time()
example.rock_bubble_sort(test_time)
end_time = time()
print(end_time - start_time)

15.355230569839478


# №16

Реализовать быструю сортировку с возможностью подсчета операций. Сравнить производительность алгоритма на случайных и упорядоченных (и почти упорядоченных) данных.

In [17]:
print(example.quick_sort(random_example))

[-851, -810, -714, -684, -458, -313, -240, -82, 135, 137, 362, 376, 418, 425, 431, 456, 493, 510, 646, 953]


случайный список

In [18]:
start_time = time()
example.quick_sort(example.random_list(100000))
end_time = time()
print(end_time - start_time)

0.132645845413208


отсортированный список

In [19]:
test_time = sorted(example.random_list(100000))
start_time = time()
example.quick_sort(test_time)
end_time = time()
print(end_time - start_time)

14.657094240188599


реверсд отсортированный список

In [20]:
test_time = sorted(example.random_list(100000))[::-1]
start_time = time()
example.quick_sort(test_time)
end_time = time()
print(end_time - start_time)

14.168990850448608


частично отсортированный список

In [21]:
test_time = example.partially_sorted_list(example.random_list(100000))
start_time = time()
example.quick_sort(test_time)
end_time = time()
print(end_time - start_time)

9.176163673400879


# №17

Улучшить работу быстрой сортировки на упорядоченных и почти упорядоченных за счет изменения алгоритма выбора элемента для разделения массива.

изначально идея реализации быстрой сортировки заключается в выборе элемента, относительно которого слева и справа образуются списки больших и меньших значений, и чем больше рекурсий будет(то бишь надо выбрать средний по значению элемент), тем быстрее выполнится сортировка

In [22]:
test_time = sorted(example.random_list(100000))
start_time = time()
example.quick_sort_for_sorted(test_time)
end_time = time()
print(end_time - start_time)

6.810963869094849


# №15

In [31]:
test_time = example.random_list(10000)
start_time = time()
example.selection_sort(test_time)
end_time = time()
print(end_time - start_time)

9.501111507415771


In [32]:
test_time = sorted(example.random_list(10000))
start_time = time()
example.selection_sort(test_time)
end_time = time()
print(end_time - start_time)

3.3829569816589355


In [37]:
test_time = example.random_list(10000)
start_time = time()
example.modified_selection_sort(test_time)
end_time = time()
print(end_time - start_time)

9.5844087600708


In [38]:
test_time = sorted(example.random_list(10000))
start_time = time()
example.modified_selection_sort(test_time)
end_time = time()
print(end_time - start_time)

3.528132915496826
