# Numpy

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [136]:
import numpy as np

data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [51]:
print(data.mean(axis=0)[1:])
print(data.min(axis=0)[1:])
print(data.max(axis=0)[1:])
print(np.median(data[:, 1:], axis=0))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [91]:
print(data[data[:, 1] <= np.quantile(data[:, 2], 0.75)])

[[ 94746     10      6]
 [ 67660      5      6]
 [366174      7      9]
 ...
 [420725      5      3]
 [  4747      1      9]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [56]:
count_of_zeros = np.count_nonzero(data[:,1] == 0)
print(count_of_zeros)
data[:,1][data[:,1] == 0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [95]:
print(int(len((np.unique(data))) / 3))

33514


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [63]:
print(np.unique(data[:,2]).size)

37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [138]:
new_data = data[data[:,2] <= 5]
print(new_data)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [97]:
ingredient_per_minute = data[:,2] / data[:,1]
print(np.max(ingredient_per_minute))

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [106]:
print(data[data[:, 1].argsort()][::-1][:100])

[[    261647 2147483647          8]
 [    216215     259260          7]
 [    425681     259205          2]
 [     98912     216015          4]
 [     70551     201610          7]
 [    236340     146880          5]
 [    242032     132495          3]
 [    184528     129620          3]
 [    236274     129615          5]
 [    236281     129615          5]
 [     13264     115230          4]
 [    105417      86405          2]
 [     41403      86400          4]
 [     34175      86400          3]
 [    142936      86400          9]
 [     93063      86400          2]
 [     42247      69120          2]
 [    255611      64815          3]
 [    140344      60555          3]
 [    101082      60540          7]
 [     46288      50405          5]
 [    246196      44655          4]
 [     30845      44645          3]
 [    344480      43380         22]
 [    102098      43380          4]
 [    254782      43250         15]
 [    209590      43230          8]
 [    200097      43205     

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [110]:
random_indexes = np.random.randint(0, len(data), 10)
print(data[random_indexes])

[[282762     25      6]
 [165084     55      6]
 [359035     20     10]
 [198017      1      5]
 [499768    137     13]
 [366999     10     11]
 [264584     90     11]
 [116011     30      4]
 [352904     20     14]
 [486098     80     14]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [117]:
print((data[data[:, 2] < np.mean(data[:, 2])].size / data.size) * 100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [139]:
new_data = new_data[new_data[:,1] <= 20]
a = np.array([1]*new_data[:,1].size).reshape(new_data[:,1].size, 1)
new_data = np.append(new_data, a, axis=1)
print(new_data)

[[446597     15      5      1]
 [204134      5      3      1]
 [ 25623      6      4      1]
 ...
 [ 60756     15      5      1]
 [128811     15      4      1]
 [370915      5      4      1]]


13. Выведите процент "простых" рецептов в датасете

In [141]:
print(new_data[:,3].size)

9552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [142]:
short = data[data[:, 1] < 10]
standard = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long = data[data[:, 1] >= 20]

max_len = min(len(short), len(standard), len(long)) #максимальное кол-во рецептов в каждой группе

grouped_recipes = np.zeros((3, max_len, 3), dtype=int)
grouped_recipes[0, :len(short[:max_len])] = short[:max_len]
grouped_recipes[1, :len(standard[:max_len])] = standard[:max_len]
grouped_recipes[2, :len(long[:max_len])] = long[:max_len]

print(grouped_recipes)
print(grouped_recipes.shape)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
(3, 7588, 3)
